- name: Commit & Push
  run: |
    cd space

    echo "===== CURRENT DIRECTORY ====="
    pwd

    echo "===== FILES ====="
    ls -la

    echo "===== REMOTES ====="
    git remote -v

    git config user.email "actions@github.com"
    git config user.name "github-actions"

    git add .

    if git diff --cached --quiet; then
      echo "No changes"
      exit 0
    fi

    git commit -m "Auto deploy"

    git push